### PR TITLE
LRDOCS-12695 - List Type Client Extension for Distributor Application

### PR DESCRIPTION
**Pull request by Claudioss23**
This Pull Request adds a Batch-type Client Extension to the Clarity workspace. It creates Picklists in the Liferay Instance.

cc @tmidde324

### CODE REVIEW

**Comment by Claudioss23** [comment]
ci:stop

**Comment by Claudioss23** [comment]
ci:forward

**Comment by Claudioss23** [comment]
ci:stop

**Comment by Claudioss23** [comment]
ci:forward

**Comment by Claudioss23** [comment]
ci:stop

**Comment by Claudioss23** [comment]
ci:forward

**Comment by Claudioss23** [comment]
ci:stop

**Comment by Claudioss23** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:forward:force

**Pull request closed without merging**
